version: '3.4'

services:
  my-gateway:
    image: my-gateway
    build: .
    container_name: gateway
    depends_on: 
      - redisdb
    environment:
      NODE_ENV: production
      REDIS_HOST: redisdb
      REDIS_PORT: 6379
    ports:
      - 8080:8080

  redisdb:
    image: "redis:5-alpine"
    container_name: redis

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: phpredisadmin
    depends_on: 
      - redisdb
    environment:
      REDIS_1_HOST: redisdb
      REDIS_1_NAME: redis-gateway
    ports:
      - 8081:80